name: beats
version: 1.0.0+1
description: A full-featured music streaming app inspired by YouTube Music.
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.3
  
  # Audio playback
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audio_session: ^0.1.14
  
  # State management
  provider: ^6.0.5
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3
  
  # Network
  http: ^1.1.0
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Other
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: BeatsFont
      fonts:
        - asset: fonts/Beats-Regular.ttf
        - asset: fonts/Beats-Bold.ttf
          weight: 700